package app.hotelreservationsystem.views.reservation;

import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author JekKath
 */
public class HotelReservationSearchView extends javax.swing.JFrame {

    /**
     * Creates new form HotelReservationSearchView
     */
    public HotelReservationSearchView() {
        initComponents();
    }

    public JTable getTblReservation() {
        return tblReservation;
    }

    public void setTblReservation(JTable tblReservation) {
        this.tblReservation = tblReservation;
    }

    public JTextField getTxtReservationID() {
        return txtReservationID;
    }

    public void setTxtReservationID(JTextField txtReservationID) {
        this.txtReservationID = txtReservationID;
    }
    
    public void searchReservationByIDBtnListener(ActionListener myActionListener) {
        btnSearchReservation.addActionListener(myActionListener);
    }
    
    public void searchAllReservationsBtnListener(ActionListener myActionListener) {
        btnSearchAllReservations.addActionListener(myActionListener);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblReservationRegister = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservation = new javax.swing.JTable();
        btnSearchReservation = new javax.swing.JButton();
        txtReservationID = new javax.swing.JTextField();
        btnSearchAllReservations = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Reservation Account");

        childPanel.setBackground(java.awt.Color.white);

        lblReservationRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblReservationRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReservationRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/search.png"))); // NOI18N
        lblReservationRegister.setText("Search for Reservation");
        lblReservationRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblReservation.setAutoCreateRowSorter(true);
        tblReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reservation ID", "Customer ID", "Room ID", "Employee ID", "Check-In Date", "Check-Out Date", "Status"
            }
        ));
        tblReservation.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblReservation);

        btnSearchReservation.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/search.png"))); // NOI18N
        btnSearchReservation.setText("Search By ReservationID");
        btnSearchReservation.setToolTipText("");
        btnSearchReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReservationActionPerformed(evt);
            }
        });

        txtReservationID.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        txtReservationID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationIDActionPerformed(evt);
            }
        });

        btnSearchAllReservations.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchAllReservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/search.png"))); // NOI18N
        btnSearchAllReservations.setText("Search All");
        btnSearchAllReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllReservationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(childPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReservationRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(childPanelLayout.createSequentialGroup()
                        .addGap(0, 616, Short.MAX_VALUE)
                        .addComponent(txtReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchAllReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservationRegister)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearchReservation)
                        .addComponent(btnSearchAllReservations)))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchReservationActionPerformed

    private void txtReservationIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationIDActionPerformed

    private void btnSearchAllReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllReservationsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAllReservationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReservationSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReservationSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReservationSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReservationSearchView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReservationSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchAllReservations;
    private javax.swing.JButton btnSearchReservation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservation;
    private javax.swing.JTextField txtReservationID;
    // End of variables declaration//GEN-END:variables
}
