package app.hotelreservationsystem.views.reservation;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author JekKath
 */
public class HotelReservationUpdateView extends javax.swing.JFrame {

    /**
     * Creates new form HotelReservationUpdateView
     */
    public HotelReservationUpdateView() {
        initComponents();
    }

    public JTextField getTxtReservationCheckInDate() {
        return txtReservationCheckInDate;
    }

    public void setTxtReservationCheckInDate(JTextField txtReservationCheckInDate) {
        this.txtReservationCheckInDate = txtReservationCheckInDate;
    }

    public JTextField getTxtReservationCheckOutDate() {
        return txtReservationCheckOutDate;
    }

    public void setTxtReservationCheckOutDate(JTextField txtReservationCheckOutDate) {
        this.txtReservationCheckOutDate = txtReservationCheckOutDate;
    }

    public JTextField getTxtReservationCustomerID() {
        return txtReservationCustomerID;
    }

    public void setTxtReservationCustomerID(JTextField txtReservationCustomerID) {
        this.txtReservationCustomerID = txtReservationCustomerID;
    }

    public JTextField getTxtReservationID() {
        return txtReservationID;
    }

    public void setTxtReservationID(JTextField txtReservationID) {
        this.txtReservationID = txtReservationID;
    }


    public JTextField getTxtReservationEmployeeID() {
        return txtReservationEmployeeID;
    }

    public void setTxtReservationEmployeeID(JTextField txtReservationEmployeeID) {
        this.txtReservationEmployeeID = txtReservationEmployeeID;
    }

    public JTextField getTxtReservationRoomID() {
        return txtReservationRoomID;
    }

    public void setTxtReservationRoomID(JTextField txtReservationRoomID) {
        this.txtReservationRoomID = txtReservationRoomID;
    }

    public JTextField getTxtReservationStatus() {
        return txtReservationStatus;
    }

    public void setTxtReservationStatus(JTextField txtReservationStatus) {
        this.txtReservationStatus = txtReservationStatus;
    }
    
    
    
    public void updateReservationBtnListener(ActionListener myActionListener){
        btnUpdateReservation.addActionListener(myActionListener);
    }
   
    public void getReservationInfoBtnListener(ActionListener myActionListener){
        btnGetReservationInfo.addActionListener(myActionListener);
    }
    
    public void clearAllBtnListener(ActionListener myActionListener){
        btnClear.addActionListener(myActionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegistrationCustomerID = new javax.swing.JLabel();
        txtReservationCustomerID = new javax.swing.JTextField();
        javax.swing.JLabel lblRegistrationRoomID = new javax.swing.JLabel();
        txtReservationRoomID = new javax.swing.JTextField();
        javax.swing.JLabel lblAddress = new javax.swing.JLabel();
        txtReservationEmployeeID = new javax.swing.JTextField();
        javax.swing.JLabel lblPhone = new javax.swing.JLabel();
        txtReservationCheckOutDate = new javax.swing.JTextField();
        javax.swing.JLabel lblEmail = new javax.swing.JLabel();
        txtReservationStatus = new javax.swing.JTextField();
        javax.swing.JLabel lblBillingAddress = new javax.swing.JLabel();
        txtReservationCheckInDate = new javax.swing.JTextField();
        btnUpdateReservation = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        javax.swing.JLabel lblUpdateReservation = new javax.swing.JLabel();
        javax.swing.JPanel getReservationInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegistrationCustomerID1 = new javax.swing.JLabel();
        txtReservationID = new javax.swing.JTextField();
        btnGetReservationInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Reservation Account");

        childPanel.setBackground(java.awt.Color.white);

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblRegistrationCustomerID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRegistrationCustomerID.setText("Customer ID:");

        lblRegistrationRoomID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRegistrationRoomID.setText("Room ID:");

        lblAddress.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblAddress.setText("Employee ID:");

        lblPhone.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPhone.setText("Check-Out Date:");

        txtReservationCheckOutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationCheckOutDateActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmail.setText("Status:");

        txtReservationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationStatusActionPerformed(evt);
            }
        });

        lblBillingAddress.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBillingAddress.setText("Check-In Date:");

        btnUpdateReservation.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnUpdateReservation.setFont(btnUpdateReservation.getFont());
        btnUpdateReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/update.png"))); // NOI18N
        btnUpdateReservation.setText("Update");
        btnUpdateReservation.setPreferredSize(new java.awt.Dimension(112, 24));
        btnUpdateReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReservationActionPerformed(evt);
            }
        });

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClear.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrationCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationCustomerID)
                    .addComponent(lblRegistrationRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationRoomID)
                    .addComponent(lblAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationEmployeeID)
                    .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationCheckOutDate)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationStatus)
                    .addComponent(lblBillingAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationCheckInDate)
                    .addGroup(enterInfoPanelLayout.createSequentialGroup()
                        .addComponent(btnUpdateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegistrationCustomerID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistrationRoomID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBillingAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear)))
        );

        lblUpdateReservation.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblUpdateReservation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/update.png"))); // NOI18N
        lblUpdateReservation.setText("Update Reservation Account:");
        lblUpdateReservation.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        getReservationInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get Reservation Info:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        getReservationInfoPanel.setOpaque(false);

        lblRegistrationCustomerID1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRegistrationCustomerID1.setText("Reservation ID:");

        btnGetReservationInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnGetReservationInfo.setFont(btnGetReservationInfo.getFont());
        btnGetReservationInfo.setText("Get Info");
        btnGetReservationInfo.setRolloverEnabled(false);
        btnGetReservationInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetReservationInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getReservationInfoPanelLayout = new javax.swing.GroupLayout(getReservationInfoPanel);
        getReservationInfoPanel.setLayout(getReservationInfoPanelLayout);
        getReservationInfoPanelLayout.setHorizontalGroup(
            getReservationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getReservationInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(getReservationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistrationCustomerID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationID)
                    .addGroup(getReservationInfoPanelLayout.createSequentialGroup()
                        .addComponent(btnGetReservationInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        getReservationInfoPanelLayout.setVerticalGroup(
            getReservationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getReservationInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrationCustomerID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGetReservationInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateReservation, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addComponent(getReservationInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdateReservation)
                .addGap(18, 18, 18)
                .addComponent(getReservationInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReservationCheckOutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationCheckOutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationCheckOutDateActionPerformed

    private void txtReservationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationStatusActionPerformed

    private void btnUpdateReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReservationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateReservationActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGetReservationInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetReservationInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetReservationInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReservationUpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReservationUpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReservationUpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReservationUpdateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReservationUpdateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGetReservationInfo;
    private javax.swing.JButton btnUpdateReservation;
    private javax.swing.JTextField txtReservationCheckInDate;
    private javax.swing.JTextField txtReservationCheckOutDate;
    private javax.swing.JTextField txtReservationCustomerID;
    private javax.swing.JTextField txtReservationEmployeeID;
    private javax.swing.JTextField txtReservationID;
    private javax.swing.JTextField txtReservationRoomID;
    private javax.swing.JTextField txtReservationStatus;
    // End of variables declaration//GEN-END:variables
}
