package app.hotelreservationsystem.views.booking;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author kale and felix
 */

public class HotelBookingUpdateView extends javax.swing.JFrame {

    /**
     * Creates new form HotelStaffView
     */
    public HotelBookingUpdateView() {
        initComponents();
    }

    public JButton getBtnClearAll() {
        return btnClearAll;
    }

    public void setBtnClearAll(JButton btnClearAll) {
        this.btnClearAll = btnClearAll;
    }

    public JButton getBtnUpdateFields() {
        return btnUpdateFields;
    }

    public void setBtnUpdateFields(JButton btnUpdateFields) {
        this.btnUpdateFields = btnUpdateFields;
    }

    public JTextField getTxtDate() {
        return txtDate;
    }

    public void setTxtDate(JFormattedTextField txtDate) {
        this.txtDate = txtDate;
    }

    public JTextField getTxtPrice() {
        return txtPrice;
    }

    public void setTxtPrice(JTextField txtPrice) {
        this.txtPrice = txtPrice;
    }

    public JTextField getTxtReservationId() {
        return txtReservationId;
    }

    public JTextField getTxtBookingID() {
        return txtBookingID;
    }

    public void setTxtBookingID(JTextField txtBookingID) {
        this.txtBookingID = txtBookingID;
    }
    
    

    public void setTxtReservationId(JTextField txtReservationId) {
        this.txtReservationId = txtReservationId;
    }
    
    public void updateBookingBtnListener(ActionListener myActionListener){
        btnUpdateFields.addActionListener(myActionListener);
    }
   
    public void getBookingInfoBtnListener(ActionListener myActionListener){
        btnGetBookingInfo.addActionListener(myActionListener);
    }
    
    public void clearAllBtnListener(ActionListener myActionListener){
        btnClearAll.addActionListener(myActionListener);
    }

   
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegister = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblReservationId = new javax.swing.JLabel();
        txtReservationId = new javax.swing.JTextField();
        javax.swing.JLabel lblBookingDate = new javax.swing.JLabel();
        javax.swing.JLabel lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdateFields = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        txtDate = new javax.swing.JFormattedTextField();
        javax.swing.JPanel getBookingInfo = new javax.swing.JPanel();
        javax.swing.JLabel lblBookingID = new javax.swing.JLabel();
        txtBookingID = new javax.swing.JTextField();
        btnGetBookingInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Booking");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lblRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/update.png"))); // NOI18N
        lblRegister.setText("Update Booking:");
        lblRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblReservationId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationId.setText("Reservation ID:");

        lblBookingDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBookingDate.setText("Booking Date:");

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPrice.setText("Price:");

        btnUpdateFields.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnUpdateFields.setFont(btnUpdateFields.getFont());
        btnUpdateFields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/update.png"))); // NOI18N
        btnUpdateFields.setText("Update");
        btnUpdateFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFieldsActionPerformed(evt);
            }
        });

        btnClearAll.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClearAll.setFont(btnClearAll.getFont());
        btnClearAll.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClearAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/hotelreservationsystem/views/icons/clear.png"))); // NOI18N
        btnClearAll.setText("Clear");
        btnClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearAllActionPerformed(evt);
            }
        });

        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y-MM-dd"))));
        txtDate.setText("Jan 1, 2000");
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrice)
                    .addComponent(txtReservationId)
                    .addComponent(lblReservationId, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(lblBookingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate)
                    .addGroup(enterInfoPanelLayout.createSequentialGroup()
                        .addComponent(btnUpdateFields, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClearAll)))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservationId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBookingDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateFields)
                    .addComponent(btnClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getBookingInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get Booking Info:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        getBookingInfo.setOpaque(false);

        lblBookingID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBookingID.setText("Booking ID:");

        btnGetBookingInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnGetBookingInfo.setFont(btnGetBookingInfo.getFont());
        btnGetBookingInfo.setText("Get Booking Info");
        btnGetBookingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBookingInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getBookingInfoLayout = new javax.swing.GroupLayout(getBookingInfo);
        getBookingInfo.setLayout(getBookingInfoLayout);
        getBookingInfoLayout.setHorizontalGroup(
            getBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getBookingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(getBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBookingID)
                    .addComponent(lblBookingID, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addGroup(getBookingInfoLayout.createSequentialGroup()
                        .addComponent(btnGetBookingInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        getBookingInfoLayout.setVerticalGroup(
            getBookingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getBookingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookingID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnGetBookingInfo)
                .addContainerGap())
        );

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addComponent(getBookingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getBookingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getBookingInfo.getAccessibleContext().setAccessibleName("Get Booking Info");

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateFieldsActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnGetBookingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBookingInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetBookingInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelBookingUpdateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnGetBookingInfo;
    private javax.swing.JButton btnUpdateFields;
    private javax.swing.JTextField txtBookingID;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtReservationId;
    // End of variables declaration//GEN-END:variables
}
