/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author kale
 */

public class HotelBookingAddView extends javax.swing.JFrame {

    /**
     * Creates new form HotelStaffView
     */
    public HotelBookingAddView() {
        initComponents();
    }

    public JButton getBtnAddBooking() {
        return btnAddBooking;
    }

    public void setBtnAddBooking(JButton btnAddBooking) {
        this.btnAddBooking = btnAddBooking;
    }

    public JButton getBtnClearBooking() {
        return btnClearBooking;
    }

    public void setBtnClearBooking(JButton btnClearBooking) {
        this.btnClearBooking = btnClearBooking;
    }

    public JFormattedTextField getTxtDate() {
        return txtDate;
    }

    public void setTxtDate(JFormattedTextField txtDate) {
        this.txtDate = txtDate;
    }

    public JFormattedTextField getTxtFormatPrice() {
        return txtFormatPrice;
    }

    public void setTxtFormatPrice(JFormattedTextField txtFormatPrice) {
        this.txtFormatPrice = txtFormatPrice;
    }

    public JTextField getTxtReservationId() {
        return txtReservationId;
    }

    public void setTxtReservationId(JTextField txtReservationId) {
        this.txtReservationId = txtReservationId;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblAddBooking = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblReservationId = new javax.swing.JLabel();
        txtReservationId = new javax.swing.JTextField();
        javax.swing.JLabel lblBookingDate = new javax.swing.JLabel();
        btnClearBooking = new javax.swing.JButton();
        btnAddBooking = new javax.swing.JButton();
        javax.swing.JLabel lblPrice = new javax.swing.JLabel();
        txtFormatPrice = new javax.swing.JFormattedTextField();
        txtDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Booking");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lblAddBooking.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblAddBooking.setForeground(java.awt.Color.black);
        lblAddBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/sleeping.png"))); // NOI18N
        lblAddBooking.setText("Create Booking Record");
        lblAddBooking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14), java.awt.Color.black)); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblReservationId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationId.setForeground(java.awt.Color.black);
        lblReservationId.setText("Reservation ID");

        lblBookingDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBookingDate.setForeground(java.awt.Color.black);
        lblBookingDate.setText("Set Booking Date");

        btnClearBooking.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClearBooking.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClearBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/clear.png"))); // NOI18N
        btnClearBooking.setText("Clear");

        btnAddBooking.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnAddBooking.setForeground(new java.awt.Color(0, 0, 0));
        btnAddBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/add.png"))); // NOI18N
        btnAddBooking.setText("Register");

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPrice.setForeground(java.awt.Color.black);
        lblPrice.setText("Price Set:");

        txtFormatPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFormatPrice)
                    .addComponent(lblReservationId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationId)
                    .addComponent(lblBookingDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 425, Short.MAX_VALUE)
                        .addComponent(btnAddBooking)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearBooking))
                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservationId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBookingDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBooking)
                    .addComponent(btnClearBooking))
                .addContainerGap())
        );

        btnClearBooking.getAccessibleContext().setAccessibleParent(this);
        btnAddBooking.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelBookingAddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBooking;
    private javax.swing.JButton btnClearBooking;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JFormattedTextField txtFormatPrice;
    private javax.swing.JTextField txtReservationId;
    // End of variables declaration//GEN-END:variables
}
