/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author kale
 */

public class HotelRoomSearchView extends javax.swing.JFrame {

    /**
     * Creates new form HotelStaffView
     */
    public HotelRoomSearchView() {
        initComponents();
    }    

    public JTextField getTxtRoomID() {
        return txtRoomID;
    }

    public void setTxtRoomID(JTextField txtRoomID) {
        this.txtRoomID = txtRoomID;
    }

    public JTable getTblRooms() {
        return tblRooms;
    }

    public void setTblRooms(JTable tblRooms) {
        this.tblRooms = tblRooms;
    }

    public void searchRoomByIDBtnListener(ActionListener myActionListener){
        btnSearchRoom.addActionListener(myActionListener);
    }
    
    public void searchAllRoomsBtnListener(ActionListener myActionListener){
        btnSearchAllRooms.addActionListener(myActionListener);
    }

   
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lbSearchRoom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRooms = new javax.swing.JTable();
        btnSearchRoom = new javax.swing.JButton();
        txtRoomID = new javax.swing.JTextField();
        btnSearchAllRooms = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search User Account");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lbSearchRoom.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbSearchRoom.setForeground(java.awt.Color.black);
        lbSearchRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSearchRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/search.png"))); // NOI18N
        lbSearchRoom.setText("Search for Room");
        lbSearchRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblRooms.setAutoCreateRowSorter(true);
        tblRooms.setBackground(new java.awt.Color(255, 255, 255));
        tblRooms.setForeground(new java.awt.Color(0, 0, 0));
        tblRooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Room Number", "Room Type", "Price Per Night", "Room Status", "Updated By"
            }
        ));
        tblRooms.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblRooms);

        btnSearchRoom.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchRoom.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/search.png"))); // NOI18N
        btnSearchRoom.setText("Search By RoomID...");
        btnSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomActionPerformed(evt);
            }
        });

        txtRoomID.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        txtRoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomIDActionPerformed(evt);
            }
        });

        btnSearchAllRooms.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchAllRooms.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchAllRooms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/search.png"))); // NOI18N
        btnSearchAllRooms.setText("Search All Rooms");
        btnSearchAllRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAllRoomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(childPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSearchRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(childPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchAllRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSearchRoom)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchRoom)
                    .addComponent(btnSearchAllRooms))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomIDActionPerformed

    private void btnSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchRoomActionPerformed

    private void btnSearchAllRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAllRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAllRoomsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelRoomSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchAllRooms;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRooms;
    private javax.swing.JTextField txtRoomID;
    // End of variables declaration//GEN-END:variables
}
