package edu.dsc.hotelreservation.view;

/**
 *
 * @author JekKath
 */
public class HotelPaymentAddView extends javax.swing.JFrame {

    /**
     * Creates new form HotelPaymentAddView
     */
    public HotelPaymentAddView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegister = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblPaymentBookingID = new javax.swing.JLabel();
        txtPaymentBookingID = new javax.swing.JTextField();
        javax.swing.JLabel lblPaymentEmployeeID = new javax.swing.JLabel();
        txtPaymentEmployeeID = new javax.swing.JTextField();
        javax.swing.JLabel lblPaymentDate = new javax.swing.JLabel();
        txtPaymentDate = new javax.swing.JTextField();
        javax.swing.JLabel lblPaymentMethod = new javax.swing.JLabel();
        txtPaymentMethod = new javax.swing.JTextField();
        javax.swing.JLabel lblPaymentStatus = new javax.swing.JLabel();
        txtPaymentStatus = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAddGuest = new javax.swing.JButton();
        javax.swing.JLabel lblPaymentAmount = new javax.swing.JLabel();
        txtPaymentAmount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Payment Account");

        childPanel.setBackground(java.awt.Color.white);

        lblRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/user.png"))); // NOI18N
        lblRegister.setText("Create Payment Account:");
        lblRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblPaymentBookingID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentBookingID.setText("BookingID:");

        lblPaymentEmployeeID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentEmployeeID.setText("EmployeeID:");

        txtPaymentEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentEmployeeIDActionPerformed(evt);
            }
        });

        lblPaymentDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentDate.setText("Payment Date:");

        lblPaymentMethod.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentMethod.setText("Payment Method:");

        lblPaymentStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentStatus.setText("Status:");

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClear.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/clear.png"))); // NOI18N
        btnClear.setText("Clear");

        btnAddGuest.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnAddGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/add.png"))); // NOI18N
        btnAddGuest.setText("Register");

        lblPaymentAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPaymentAmount.setText("Amount:");

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaymentBookingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentBookingID)
                    .addComponent(lblPaymentEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentEmployeeID)
                    .addComponent(lblPaymentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentDate)
                    .addComponent(lblPaymentMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentMethod)
                    .addComponent(lblPaymentStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentStatus)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(btnAddGuest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear))
                    .addComponent(lblPaymentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaymentAmount))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPaymentBookingID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentBookingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaymentEmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaymentDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaymentAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPaymentMethod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaymentStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGuest)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentEmployeeIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelPaymentAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelPaymentAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelPaymentAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelPaymentAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelPaymentAddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGuest;
    private javax.swing.JButton btnClear;
    private javax.swing.JTextField txtPaymentAmount;
    private javax.swing.JTextField txtPaymentBookingID;
    private javax.swing.JTextField txtPaymentDate;
    private javax.swing.JTextField txtPaymentEmployeeID;
    private javax.swing.JTextField txtPaymentMethod;
    private javax.swing.JTextField txtPaymentStatus;
    // End of variables declaration//GEN-END:variables
}
