package edu.dsc.hotelreservation.view;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author kale
 */

public class HotelGuestSearchView extends javax.swing.JFrame {

    /**
     * Creates new form HotelStaffView
     */
    public HotelGuestSearchView() {
        initComponents();
    }

    public JButton getBtnSearchGuestAll() {
        return btnSearchGuestAll;
    }

    public void setBtnSearchGuestAll(JButton btnSearchGuestAll) {
        this.btnSearchGuestAll = btnSearchGuestAll;
    }

    public JButton getBtnSearchGuestId() {
        return btnSearchGuestId;
    }

    public void setBtnSearchGuestId(JButton btnSearchGuestId) {
        this.btnSearchGuestId = btnSearchGuestId;
    }

    public JTable getTblGuest() {
        return tblGuest;
    }

    public void setTblGuest(JTable tblGuest) {
        this.tblGuest = tblGuest;
    }


    public JTextField getTxtSearchGuest() {
        return txtSearchGuest;
    }

    public void setTxtSearchGuest(JTextField txtSearchGuest) {
        this.txtSearchGuest = txtSearchGuest;
    }

   public void searchGuestIdBtnListener(ActionListener myActionListener){
        btnSearchGuestId.addActionListener(myActionListener);
    }
   
    public void searchGuestAllBtnListener(ActionListener myActionListener){
        btnSearchGuestAll.addActionListener(myActionListener);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegister = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuest = new javax.swing.JTable();
        btnSearchGuestId = new javax.swing.JButton();
        txtSearchGuest = new javax.swing.JTextField();
        btnSearchGuestAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Guest Account");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lblRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/search.png"))); // NOI18N
        lblRegister.setText("Search for Guest");
        lblRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblGuest.setAutoCreateRowSorter(true);
        tblGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Guest ID", "First Name", "Last Name", "Email", "Phone", "Unit", "Street Address", "City", "Postal Code", "Country"
            }
        ));
        tblGuest.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblGuest);

        btnSearchGuestId.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchGuestId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/search.png"))); // NOI18N
        btnSearchGuestId.setText("Search By GuestID...");

        txtSearchGuest.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));

        btnSearchGuestAll.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnSearchGuestAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/search.png"))); // NOI18N
        btnSearchGuestAll.setText("Search All Guests...");

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, childPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchGuestId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchGuestAll, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchGuestId)
                    .addComponent(btnSearchGuestAll))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelGuestSearchView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchGuestAll;
    private javax.swing.JButton btnSearchGuestId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGuest;
    private javax.swing.JTextField txtSearchGuest;
    // End of variables declaration//GEN-END:variables
}
