package edu.dsc.hotelreservation.view;

import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author JekKath
 */
public class HotelReservationAddView extends javax.swing.JFrame {

    /**
     * Creates new form HotelReservationAddView
     */
    public HotelReservationAddView() {
        initComponents();
    }

    public JFormattedTextField getTxtReservationCheckInDate() {
        return txtReservationCheckInDate;
    }

    public void setTxtReservationCheckInDate(JFormattedTextField txtReservationCheckInDate) {
        this.txtReservationCheckInDate = txtReservationCheckInDate;
    }

    public JFormattedTextField getTxtReservationCheckOutDate() {
        return txtReservationCheckOutDate;
    }

    public void setTxtReservationCheckOutDate(JFormattedTextField txtReservationCheckOutDate) {
        this.txtReservationCheckOutDate = txtReservationCheckOutDate;
    }

    public JTextField getTxtReservationCustomerID() {
        return txtReservationCustomerID;
    }

    public void setTxtReservationCustomerID(JTextField txtReservationCustomerID) {
        this.txtReservationCustomerID = txtReservationCustomerID;
    }

    public JTextField getTxtReservationEmployeeID() {
        return txtReservationEmployeeID;
    }

    public void setTxtReservationEmployeeID(JTextField txtReservationEmployeeID) {
        this.txtReservationEmployeeID = txtReservationEmployeeID;
    }

    public JTextField getTxtReservationRoomID() {
        return txtReservationRoomID;
    }

    public void setTxtReservationRoomID(JTextField txtReservationRoomID) {
        this.txtReservationRoomID = txtReservationRoomID;
    }

    public JTextField getTxtReservationStatus() {
        return txtReservationStatus;
    }

    public void setTxtReservationStatus(JTextField txtReservationStatus) {
        this.txtReservationStatus = txtReservationStatus;
    }
    
    
    
    public void addReservationBtnListener(ActionListener myActionListener){
        btnAddReservation.addActionListener(myActionListener);
    }
    
    public void clearReservationBtnListener(ActionListener myActionListener){
        btnClearReservation.addActionListener(myActionListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRegister = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblReservationCustomerID = new javax.swing.JLabel();
        txtReservationCustomerID = new javax.swing.JTextField();
        javax.swing.JLabel lblReservationRoomID = new javax.swing.JLabel();
        txtReservationRoomID = new javax.swing.JTextField();
        javax.swing.JLabel lblReservationEmployeeID = new javax.swing.JLabel();
        txtReservationEmployeeID = new javax.swing.JTextField();
        javax.swing.JLabel lblReservationCheckOutDate = new javax.swing.JLabel();
        javax.swing.JLabel lblReservationStatus = new javax.swing.JLabel();
        txtReservationStatus = new javax.swing.JTextField();
        btnClearReservation = new javax.swing.JButton();
        btnAddReservation = new javax.swing.JButton();
        javax.swing.JLabel lblReservationCheckInDate = new javax.swing.JLabel();
        txtReservationCheckInDate = new javax.swing.JFormattedTextField();
        txtReservationCheckOutDate = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Reservation Account");

        childPanel.setBackground(java.awt.Color.white);

        lblRegister.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/user.png"))); // NOI18N
        lblRegister.setText("Make Reservation:");
        lblRegister.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblReservationCustomerID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationCustomerID.setText("Customer ID:");

        lblReservationRoomID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationRoomID.setText("Room ID:");

        lblReservationEmployeeID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationEmployeeID.setText("Employee ID:");

        lblReservationCheckOutDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationCheckOutDate.setText("Check-Out Date:");

        lblReservationStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationStatus.setText("Status:");

        txtReservationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationStatusActionPerformed(evt);
            }
        });

        btnClearReservation.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClearReservation.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClearReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/clear.png"))); // NOI18N
        btnClearReservation.setText("Clear");

        btnAddReservation.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnAddReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/add.png"))); // NOI18N
        btnAddReservation.setText("Reserve");

        lblReservationCheckInDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblReservationCheckInDate.setText("Check-In Date:");

        txtReservationCheckInDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y-MM-dd"))));
        txtReservationCheckInDate.setText("Jan 1, 2000");
        txtReservationCheckInDate.setToolTipText("");

        txtReservationCheckOutDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y-MM-dd"))));
        txtReservationCheckOutDate.setText("Jan 2, 2000");

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReservationCustomerID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationCustomerID)
                    .addComponent(lblReservationRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationRoomID)
                    .addComponent(lblReservationEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationEmployeeID)
                    .addComponent(lblReservationCheckOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(lblReservationStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtReservationStatus)
                    .addComponent(lblReservationCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearReservation))
                    .addComponent(txtReservationCheckInDate)
                    .addComponent(txtReservationCheckOutDate))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReservationCustomerID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReservationRoomID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReservationEmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblReservationCheckInDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblReservationCheckOutDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblReservationStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtReservationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddReservation)
                    .addComponent(btnClearReservation))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReservationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReservationStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelReservationAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelReservationAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelReservationAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelReservationAddView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelReservationAddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReservation;
    private javax.swing.JButton btnClearReservation;
    private javax.swing.JFormattedTextField txtReservationCheckInDate;
    private javax.swing.JFormattedTextField txtReservationCheckOutDate;
    private javax.swing.JTextField txtReservationCustomerID;
    private javax.swing.JTextField txtReservationEmployeeID;
    private javax.swing.JTextField txtReservationRoomID;
    private javax.swing.JTextField txtReservationStatus;
    // End of variables declaration//GEN-END:variables
}
