package edu.dsc.hotelreservation.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author felac
 */

public class HotelRoomUpdateView extends javax.swing.JFrame {

    /**
     * Creates new form HotelAddView
     */
    public HotelRoomUpdateView() {
        initComponents();
    }

    public JTextField getTxtPricePerNight() {
        return txtPricePerNight;
    }

    public void setTxtPricePerNight(JTextField txtPricePerNight) {
        this.txtPricePerNight = txtPricePerNight;
    }

    public JTextField getTxtRoomID() {
        return txtRoomID;
    }

    public void setTxtRoomID(JTextField txtRoomID) {
        this.txtRoomID = txtRoomID;
    }

    public JTextField getTxtRoomNumber() {
        return txtRoomNumber;
    }

    public void setTxtRoomNumber(JTextField txtRoomNumber) {
        this.txtRoomNumber = txtRoomNumber;
    }

    public JTextField getTxtRoomStatus() {
        return txtRoomStatus;
    }

    public void setTxtRoomStatus(JTextField txtRoomStatus) {
        this.txtRoomStatus = txtRoomStatus;
    }

    public JTextField getTxtRoomType() {
        return txtRoomType;
    }

    public void setTxtRoomType(JTextField txtRoomType) {
        this.txtRoomType = txtRoomType;
    }

    public JTextField getTxtUpdatedBy() {
        return txtUpdatedBy;
    }

    public void setTxtUpdatedBy(JTextField txtUpdatedBy) {
        this.txtUpdatedBy = txtUpdatedBy;
    }

    
    public void updateRoomBtnListener(ActionListener myActionListener){
        btnUpdateRoom.addActionListener(myActionListener);
    }
    
    public void clearAllBtnListener(ActionListener myActionListener){
        btnClear.addActionListener(myActionListener);
    }
    
    public void getRoomInfoBtnListener(ActionListener myActionListener){
        btnGetRoomInfo.addActionListener(myActionListener);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblCreateRoom = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRoomNumber = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        javax.swing.JLabel lblRoomType = new javax.swing.JLabel();
        txtRoomType = new javax.swing.JTextField();
        javax.swing.JLabel lblPricePerNight = new javax.swing.JLabel();
        txtPricePerNight = new javax.swing.JTextField();
        javax.swing.JLabel lblUpdatedBy = new javax.swing.JLabel();
        txtUpdatedBy = new javax.swing.JTextField();
        javax.swing.JLabel lblRoomStatus = new javax.swing.JLabel();
        txtRoomStatus = new javax.swing.JTextField();
        btnUpdateRoom = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        javax.swing.JPanel getRoomInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRoomID = new javax.swing.JLabel();
        txtRoomID = new javax.swing.JTextField();
        btnGetRoomInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register User Account");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lblCreateRoom.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblCreateRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/update.png"))); // NOI18N
        lblCreateRoom.setText("Update Room:");
        lblCreateRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblRoomNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomNumber.setText("Room Number:");

        lblRoomType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomType.setText("Room Type:");

        lblPricePerNight.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPricePerNight.setText("Price Per Night:");

        lblUpdatedBy.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblUpdatedBy.setText("Updated By (enter staff_id):");

        lblRoomStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomStatus.setText("Room Status:");

        btnUpdateRoom.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnUpdateRoom.setFont(btnUpdateRoom.getFont());
        btnUpdateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/update.png"))); // NOI18N
        btnUpdateRoom.setText("Update");
        btnUpdateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRoomActionPerformed(evt);
            }
        });

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClear.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomNumber)
                    .addComponent(lblRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomType)
                    .addComponent(lblPricePerNight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPricePerNight)
                    .addComponent(lblUpdatedBy, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addComponent(txtUpdatedBy)
                    .addComponent(lblRoomStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomStatus)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterInfoPanelLayout.createSequentialGroup()
                        .addComponent(btnUpdateRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRoomNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRoomType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPricePerNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPricePerNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRoomStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblUpdatedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUpdatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnUpdateRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        getRoomInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Get Room Info:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        getRoomInfoPanel.setOpaque(false);

        lblRoomID.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomID.setText("Room ID:");

        btnGetRoomInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnGetRoomInfo.setFont(btnGetRoomInfo.getFont());
        btnGetRoomInfo.setText("Get Room Info");
        btnGetRoomInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetRoomInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout getRoomInfoPanelLayout = new javax.swing.GroupLayout(getRoomInfoPanel);
        getRoomInfoPanel.setLayout(getRoomInfoPanelLayout);
        getRoomInfoPanelLayout.setHorizontalGroup(
            getRoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getRoomInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(getRoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomID)
                    .addGroup(getRoomInfoPanelLayout.createSequentialGroup()
                        .addComponent(btnGetRoomInfo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        getRoomInfoPanelLayout.setVerticalGroup(
            getRoomInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getRoomInfoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRoomID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetRoomInfo)
                .addGap(259, 259, 259))
        );

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getRoomInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreateRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getRoomInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateRoomActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnGetRoomInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRoomInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetRoomInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelRoomUpdateView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGetRoomInfo;
    private javax.swing.JButton btnUpdateRoom;
    private javax.swing.JTextField txtPricePerNight;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtRoomStatus;
    private javax.swing.JTextField txtRoomType;
    private javax.swing.JTextField txtUpdatedBy;
    // End of variables declaration//GEN-END:variables
}
