package edu.dsc.hotelreservation.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author felac
 */

public class HotelRoomAddView extends javax.swing.JFrame {

    /**
     * Creates new form HotelAddView
     */
    public HotelRoomAddView() {
        initComponents();
    }

    public JTextField getTxtPricePerNight() {
        return txtPricePerNight;
    }

    public void setTxtPricePerNight(JTextField txtPricePerNight) {
        this.txtPricePerNight = txtPricePerNight;
    }

    public JTextField getTxtRoomNumber() {
        return txtRoomNumber;
    }

    public void setTxtRoomNumber(JTextField txtRoomNumber) {
        this.txtRoomNumber = txtRoomNumber;
    }

    public JTextField getTxtRoomStatus() {
        return txtRoomStatus;
    }

    public void setTxtRoomStatus(JTextField txtRoomStatus) {
        this.txtRoomStatus = txtRoomStatus;
    }

    public JTextField getTxtRoomType() {
        return txtRoomType;
    }

    public void setTxtRoomType(JTextField txtRoomType) {
        this.txtRoomType = txtRoomType;
    }

    public JTextField getTxtUpdatedBy() {
        return txtUpdatedBy;
    }

    public void setTxtUpdatedBy(JTextField txtUpdatedBy) {
        this.txtUpdatedBy = txtUpdatedBy;
    }

    public void addRoomBtnListener(ActionListener myActionListener){
        btnAddRoom.addActionListener(myActionListener);
    }
    
    public void clearAllBtnListener(ActionListener myActionListener){
        btnClear.addActionListener(myActionListener);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel parentPanel = new javax.swing.JPanel();
        javax.swing.JPanel childPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblCreateRoom = new javax.swing.JLabel();
        javax.swing.JPanel enterInfoPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblRoomNumber = new javax.swing.JLabel();
        txtRoomNumber = new javax.swing.JTextField();
        javax.swing.JLabel lblRoomType = new javax.swing.JLabel();
        txtRoomType = new javax.swing.JTextField();
        javax.swing.JLabel lblPricePerNight = new javax.swing.JLabel();
        txtPricePerNight = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnAddRoom = new javax.swing.JButton();
        javax.swing.JLabel lblRoomStatus = new javax.swing.JLabel();
        txtUpdatedBy = new javax.swing.JTextField();
        txtRoomStatus = new javax.swing.JTextField();
        javax.swing.JLabel lblUpdatedBy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register User Account");

        parentPanel.setBackground(java.awt.Color.white);

        childPanel.setBackground(java.awt.Color.white);

        lblCreateRoom.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblCreateRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/user.png"))); // NOI18N
        lblCreateRoom.setText("Create Room:");
        lblCreateRoom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        enterInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        enterInfoPanel.setOpaque(false);

        lblRoomNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomNumber.setText("Room Number:");

        lblRoomType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomType.setText("Room Type:");

        lblPricePerNight.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPricePerNight.setText("Price Per Night:");

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnClear.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/clear.png"))); // NOI18N
        btnClear.setText("Clear");

        btnAddRoom.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        btnAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/dsc/hotelreservation/view/icons/add.png"))); // NOI18N
        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        lblRoomStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRoomStatus.setText("Room Status:");

        txtUpdatedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatedByActionPerformed(evt);
            }
        });

        txtRoomStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomStatusActionPerformed(evt);
            }
        });

        lblUpdatedBy.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblUpdatedBy.setText("Updated By:");

        javax.swing.GroupLayout enterInfoPanelLayout = new javax.swing.GroupLayout(enterInfoPanel);
        enterInfoPanel.setLayout(enterInfoPanelLayout);
        enterInfoPanelLayout.setHorizontalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoomNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomNumber)
                    .addComponent(lblRoomType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomType)
                    .addComponent(lblPricePerNight, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(txtPricePerNight)
                    .addComponent(lblRoomStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUpdatedBy)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterInfoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear))
                    .addComponent(lblUpdatedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRoomStatus))
                .addContainerGap())
        );
        enterInfoPanelLayout.setVerticalGroup(
            enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterInfoPanelLayout.createSequentialGroup()
                .addComponent(lblRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRoomType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPricePerNight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPricePerNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRoomStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoomStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUpdatedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUpdatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(enterInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRoom)
                    .addComponent(btnClear))
                .addGap(0, 0, 0))
        );

        btnClear.getAccessibleContext().setAccessibleParent(this);
        btnAddRoom.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout childPanelLayout = new javax.swing.GroupLayout(childPanel);
        childPanel.setLayout(childPanelLayout);
        childPanelLayout.setHorizontalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(enterInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        childPanelLayout.setVerticalGroup(
            childPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(childPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(childPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addComponent(childPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void txtUpdatedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatedByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatedByActionPerformed

    private void txtRoomStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelRoomAddView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnClear;
    private javax.swing.JTextField txtPricePerNight;
    private javax.swing.JTextField txtRoomNumber;
    private javax.swing.JTextField txtRoomStatus;
    private javax.swing.JTextField txtRoomType;
    private javax.swing.JTextField txtUpdatedBy;
    // End of variables declaration//GEN-END:variables
}
